name: Sync to SourceCraft

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Push to SourceCraft
        run: |
          git remote add sourcecraft https://anyname:${{ secrets.SOURCECRAFT_TOKEN }}@git.sourcecraft.dev/loynoa1/configurable-automl-engine.git
          git push sourcecraft main